include:
  - path:
      - ${LESMOTS_PATH}containers/app.yml
      - ${LESMOTS_PATH}containers/orchestrator.yml
      - ${LESMOTS_PATH}containers/database.yml
      - ${LESMOTS_PATH}containers/database_administration.yml
      - ${LESMOTS_PATH}containers/${ENV}/app.yml
      - ${LESMOTS_PATH}containers/${ENV}/orchestrator.yml
    env_file:
      - ${LESMOTS_PATH}.env
